# This Azure DevOps Pipeline automates the build and deployment process for a web application.
# It consists of two stages: 'Build' and 'Deploy'. The 'Build' stage compiles and publishes
# the web application, while the 'Deploy' stage deploys the application to an Azure App Service.
# author : Mr. Sallemi Elkamel

trigger:
- release

variables:
  buildConfiguration: 'Release'
  releaseBranchName: 'release'

schedules:
- cron: '16 23 * * *'
  displayName: 'Deploy every day at 11:11 P.M.'
  branches:
    include:
    - release
  always: false 

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      name: 'Default'

    steps:
    # Step 1: Use the specified version of .NET Core SDK
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk 6.x'
      inputs:
        version: 6.x

    # Step 2: Restore project dependencies
    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    # Step 3: Build the project using the specified build configuration
    - task: DotNetCoreCLI@2
      displayName: 'Build the project - $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration $(buildConfiguration)'
        projects: '**/*.csproj'

    # Step 4: Publish the project to the specified output directory
    - task: DotNetCoreCLI@2
      displayName: 'Publish the project - $(buildConfiguration)'
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true

    # Step 5: Publish the build artifacts for deployment
    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop

- stage: 'Dev'
  displayName: 'Deploy to the dev environment'
  dependsOn: Build
  condition: |
    and
    (
      succeeded(),
      eq(variables['Build.SourceBranchName'], variables['releaseBranchName'])
    )
  jobs:
  - deployment: Deploy
    pool:
      name: 'Default'
    environment: dev
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          # Step 6: Download the published artifacts from the Build stage
          - download: current
            artifact: drop

          # Step 7: Deploy the application to Azure App Service
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website Dev'
            inputs:
              azureSubscription: 'Resource-management-CodeHub'
              appName: '$(WebAppNameDev)'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'

- stage: 'Test'
  displayName: 'Deploy to the test environment'
  dependsOn: Dev
  #condition: eq(variables['Build.Reason'], 'Schedule')
  jobs:
  - deployment: Deploy
    pool:
      name: 'Default'
    environment: test
    variables:
    - group: 'Release'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website Test'
            inputs:
              azureSubscription: 'Resource-management-CodeHub'
              appName: '$(WebAppNameTest)'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'

- stage: 'Staging'
  displayName: 'Deploy to the staging environment'
  dependsOn: Test
  jobs:
  - deployment: Deploy
    pool:
      name: 'Default'
    environment: staging
    variables:
    - group: 'Release'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website Release'
            inputs:
              azureSubscription: 'Resource-management-CodeHub'
              appName: '$(WebAppNameStaging)'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'

# author :  Mr. Sallemi Elkamel
